/**
 * `pnpm blocks` — print the vocabulary, from the vocabulary.
 *
 * The reference has to be GENERATED. A hand-written list of what the agent can
 * render is wrong three pull requests later — four kinds and two fields were
 * added in two days — and a stale reference is worse than none, because a
 * recipe written against it names blocks that do not exist.
 *
 * So this reads `BLOCK_DOCS` beside the validator and writes the file. The
 * test that every kind has an entry is what makes it complete; this is what
 * makes it readable.
 */
import { writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { BLOCK_DOCS, BLOCK_KINDS, type BlockKind } from "@perpetual/shared/blocks";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const OUT = join(REPO, "docs", "ui-elements.md");

/** The groups are how a person looks for one, not how the type union is ordered. */
const GROUPS: { title: string; note: string; kinds: BlockKind[] }[] = [
  {
    title: "Structure",
    note: "What a page is made of at the top level.",
    kinds: ["heading", "section"],
  },
  {
    title: "Words",
    note: "Prose is the default, not the fallback.",
    kinds: ["prose", "quote", "list", "note", "code"],
  },
  {
    title: "Numbers",
    note: "Only when the content genuinely is that shape.",
    kinds: ["metrics", "chart", "table"],
  },
  {
    title: "Shapes of an idea",
    note: "For relationships prose has to work hard to describe.",
    kinds: ["split", "flow", "figure"],
  },
  {
    title: "Interaction",
    note: "The reader answers by touching, never by being asked to type.",
    kinds: ["choice", "next", "link"],
  },
  {
    title: "The app quartet",
    note: "Workspaces only — a page is a record, and a record cannot act.",
    kinds: ["rows", "fields", "form", "confirm"],
  },
];

function render(): string {
  const out: string[] = [];
  out.push("# UI elements");
  out.push("");
  out.push("**Generated by `pnpm blocks` from `packages/shared/src/blocks.ts`. Do not edit.**");
  out.push("");
  out.push(
    "Everything the agent can put on screen is one of these. It never writes HTML, CSS,",
    "colours or sizes: it picks what a thing IS, and the stylesheet decides how it looks.",
    "That split is why a session of twelve sections reads as one website — and it is the",
    "reliability engine, because a model that cannot emit a layout cannot emit a broken one.",
  );
  out.push("");
  out.push("Any block may also carry:");
  out.push("");
  out.push("| field | what it does |");
  out.push("|---|---|");
  out.push("| `id` | a name, unique within its section. Named blocks are updated one at a "
    + "time; the rule is all-or-nothing per section. |");
  out.push("| `supersedes` | `\"002-margins/numbers\"` — the block this one replaces. "
    + "Published sections are sealed, so this is how a correction works. |");
  out.push("");

  const seen = new Set<BlockKind>();
  for (const g of GROUPS) {
    out.push(`## ${g.title}`);
    out.push("");
    out.push(g.note);
    out.push("");
    for (const kind of g.kinds) {
      seen.add(kind);
      const d = BLOCK_DOCS[kind];
      out.push(`### \`${kind}\`${d.only === "workspace" ? "  · workspace only" : ""}`);
      out.push("");
      out.push(d.purpose);
      out.push("");
      out.push("```json");
      out.push(d.example);
      out.push("```");
      if (d.limits) { out.push(""); out.push(`**Limits.** ${d.limits}`); }
      out.push("");
    }
  }

  // A kind with no group is still a kind. Better an ugly appendix than a
  // silent omission from the one document that claims to be complete.
  const ungrouped = BLOCK_KINDS.filter((k) => !seen.has(k));
  if (ungrouped.length) {
    out.push("## Not yet grouped");
    out.push("");
    for (const kind of ungrouped) {
      out.push(`### \`${kind}\``);
      out.push("");
      out.push(BLOCK_DOCS[kind].purpose);
      out.push("");
    }
  }

  out.push("---");
  out.push("");
  out.push(`${BLOCK_KINDS.length} kinds. Inline, inside text, there are exactly three marks: `
    + "`**bold**` names a term, `*italic*` stresses a word, `` `code` `` is an exact value. "
    + "Nothing else renders.");
  out.push("");
  return out.join("\n");
}

await writeFile(OUT, render(), "utf8");
console.log(`wrote ${OUT} — ${BLOCK_KINDS.length} kinds`);
